[package]
name = "dino-park-lookout"
version = "0.1.0"
authors = ["Florian Merz <flomerz@gmail.com>"]
edition = "2018"

[dependencies]
#cis_client = { git = "https://github.com/fiji-flo/cis_client-rust" }
cis_client = { path = "../cis_client-rust" }
cis_profile = { git = "https://github.com/fiji-flo/cis_profile-rust", features = ["aws", "vendored"] }
actix = "0.7"
actix-web = "0.7"
futures = "0.1"
log = "0.4"
env_logger = "0.6"
serde = "1.0.80"
serde_json = "1.0.32"
serde_derive = "1.0.80"
reqwest = "0.9.8"
chrono = "0.4.6"
config = "0.9"